### ISSUE TITLE
Purpose of repo

### ISSUE THREAD

**Issue by aHodarcovs** [craiglyoung/yiimp_installation_script#5]
Hi, craig.
Are you trying to get yiimp on ubuntu?
I mean what is your goal here?
Curious, if you want to colab, if we are going for same goal. :)

**Comment by craiglyoung** [comment]
This is simply an update to the Yiimp installation to support Ubuntu 22.04 since it has largely been forgotten about by the community and still requires Ubuntu 18.04 to be used. 18.04 is end-of-support, so this installation script fork (and associated Yiimp repo) is intended to update it to be used on Ubuntu 22.04.

**Comment by aHodarcovs** [comment]
I see. Well I think you did a good job here then. 
I installed it on fresh ubuntu 22. On google cloud preinstalled vm...
And it setup fine. I think. Havent tested much yet though.

I wanted to see if I can figure out how to add new algo support to yiimp, and was going through forks, wondering if I meet someone with same thing in mind.

**Comment by craiglyoung** [comment]
For this particular repo, the intention is just to move it up to 22.04 so that the community can keep using it, and not be forced to use an unsupported Ubuntu version.   Adding algos can be quite complex and is a bit out of scope for the intention of this repo at this stage.
