### ISSUE TITLE
mkdir(): No such file or directory

### ISSUE THREAD

**Issue by roamloki** [craiglyoung/yiimp_installation_script#6]
mkdir(): No such file or directory

**Comment by craiglyoung** [comment]
Please provide details, simply stating "mkdir(): No such file or directory" helps in no way. Will mark as complete if no further info is provided.

**Comment by roamloki** [comment]
> 请提供详细信息，仅说明“mkdir()：没有此类文件或目录”毫无帮助。如果未提供进一步信息，将标记为完成。

Olny phpmyadmin can open
http://aipool.me/

**Comment by craiglyoung** [comment]
It would appear that you most likely have a permissions problem. What do your logs tell you is happening? You can check both the logs in /var/logs and also in your Yiimp screens (do a screen -ls), specifically your debug screen. What is that telling you is going on, where can it not access? I have used this script many times successfully so it may be a certain step that has been missed.

I am suspecting this is your backup folder that can't be accessed, but it is only a hunch.

**Comment by roamloki** [comment]
No Sockets found in /run/screen/S-root.
nothing in debug.log

**Comment by craiglyoung** [comment]
Just to confirm, you ran the screen command while logged in as the pool user, right? Looks to be root?

If you did do this under the pool user, and it showed no screens, I would recommend rebuilding the server and trying again as one of the steps must have either missed or didn't work right.  We could troubleshoot it, but it probably isn't worth the effort to be honest (since I know the script does work). Let me know if the same problem comes back again.

**Comment by roamloki** [comment]
ok
